/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design_7;

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlMain = new java.awt.Panel();
        lblKmToMeterTitle = new java.awt.Label();
        txxFeet = new java.awt.TextField();
        btnKmtoM = new java.awt.Button();
        lblFeetToInchesAns = new java.awt.Label();
        lblFeetToInchesTitle = new java.awt.Label();
        txtKm1 = new java.awt.TextField();
        btnFeetToInches = new java.awt.Button();
        lblKmToMAns = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(153, 153, 255));

        lblKmToMeterTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblKmToMeterTitle.setText("Km to Meter converter");

        txxFeet.setBackground(new java.awt.Color(0, 51, 204));
        txxFeet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txxFeet.setForeground(new java.awt.Color(242, 242, 242));
        txxFeet.setText("textField1");
        txxFeet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txxFeetActionPerformed(evt);
            }
        });

        btnKmtoM.setActionCommand("btnKmtoM");
        btnKmtoM.setBackground(new java.awt.Color(0, 0, 255));
        btnKmtoM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnKmtoM.setForeground(new java.awt.Color(242, 242, 242));
        btnKmtoM.setLabel("Convert");
        btnKmtoM.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnKmtoMActionPerformed(evt);
            }
        });

        lblFeetToInchesAns.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFeetToInchesAns.setText("Answer");

        lblFeetToInchesTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFeetToInchesTitle.setText("Feet To Inches converter");

        txtKm1.setBackground(new java.awt.Color(0, 51, 204));
        txtKm1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtKm1.setForeground(new java.awt.Color(242, 242, 242));
        txtKm1.setText("textField1");

        btnFeetToInches.setActionCommand("btnKmtoM");
        btnFeetToInches.setBackground(new java.awt.Color(0, 0, 255));
        btnFeetToInches.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnFeetToInches.setForeground(new java.awt.Color(242, 242, 242));
        btnFeetToInches.setLabel("Convert");
        btnFeetToInches.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFeetToInchesActionPerformed(evt);
            }
        });

        lblKmToMAns.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblKmToMAns.setText("Answer");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKmToMeterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKmToMAns, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKmtoM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txxFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeetToInchesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFeetToInchesAns, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFeetToInches, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(txtKm1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKmToMeterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeetToInchesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(txxFeet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKmtoM, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFeetToInches, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKmToMAns, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeetToInchesAns, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(txtKm1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKmtoMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnKmtoMActionPerformed
    {//GEN-HEADEREND:event_btnKmtoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKmtoMActionPerformed

    private void btnFeetToInchesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFeetToInchesActionPerformed
    {//GEN-HEADEREND:event_btnFeetToInchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFeetToInchesActionPerformed

    private void txxFeetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txxFeetActionPerformed
    {//GEN-HEADEREND:event_txxFeetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txxFeetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnFeetToInches;
    private java.awt.Button btnKmtoM;
    private java.awt.Label lblFeetToInchesAns;
    private java.awt.Label lblFeetToInchesTitle;
    private java.awt.Label lblKmToMAns;
    private java.awt.Label lblKmToMeterTitle;
    private java.awt.Panel pnlMain;
    private java.awt.TextField txtKm1;
    private java.awt.TextField txxFeet;
    // End of variables declaration//GEN-END:variables
}
