/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design_2;

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame implements Runnable
{ 
    volatile public boolean val=true;
    MainFrame f ;
    Thread t1,t2,t3 ;
    long ct =1 ;
    long ctx=1;
   long milli=0,sec=0,min=0;
   long de=0;
    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        f=this;
        t1 = new Thread(f);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlMain = new java.awt.Panel();
        pnlTitle = new java.awt.Panel();
        label1 = new java.awt.Label();
        pnlshowSeconds = new java.awt.Panel();
        lblSecondsShow = new java.awt.Label();
        pnlShowMilliSeconds = new java.awt.Panel();
        lblMilliSecondsShow = new java.awt.Label();
        pnlshowMinutes = new java.awt.Panel();
        lblMinutesShow = new java.awt.Label();
        lblMinutes = new java.awt.Label();
        lblSeconds = new java.awt.Label();
        lblMilliSeconds = new java.awt.Label();
        btnStop = new java.awt.Button();
        btnReset = new java.awt.Button();
        btnStart2 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(0, 161, 153));

        pnlTitle.setBackground(new java.awt.Color(0, 255, 255));

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 108, 102));
        label1.setText("STOPWATCH");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlshowSeconds.setBackground(new java.awt.Color(0, 255, 255));

        lblSecondsShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblSecondsShow.setForeground(new java.awt.Color(0, 161, 153));
        lblSecondsShow.setText("01");

        javax.swing.GroupLayout pnlshowSecondsLayout = new javax.swing.GroupLayout(pnlshowSeconds);
        pnlshowSeconds.setLayout(pnlshowSecondsLayout);
        pnlshowSecondsLayout.setHorizontalGroup(
            pnlshowSecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlshowSecondsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSecondsShow, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlshowSecondsLayout.setVerticalGroup(
            pnlshowSecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshowSecondsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblSecondsShow, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlShowMilliSeconds.setBackground(new java.awt.Color(0, 255, 255));

        lblMilliSecondsShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMilliSecondsShow.setForeground(new java.awt.Color(0, 161, 153));
        lblMilliSecondsShow.setText("01");

        javax.swing.GroupLayout pnlShowMilliSecondsLayout = new javax.swing.GroupLayout(pnlShowMilliSeconds);
        pnlShowMilliSeconds.setLayout(pnlShowMilliSecondsLayout);
        pnlShowMilliSecondsLayout.setHorizontalGroup(
            pnlShowMilliSecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowMilliSecondsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMilliSecondsShow, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlShowMilliSecondsLayout.setVerticalGroup(
            pnlShowMilliSecondsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowMilliSecondsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMilliSecondsShow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pnlshowMinutes.setBackground(new java.awt.Color(0, 255, 255));

        lblMinutesShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMinutesShow.setForeground(new java.awt.Color(0, 161, 153));
        lblMinutesShow.setText("00");

        javax.swing.GroupLayout pnlshowMinutesLayout = new javax.swing.GroupLayout(pnlshowMinutes);
        pnlshowMinutes.setLayout(pnlshowMinutesLayout);
        pnlshowMinutesLayout.setHorizontalGroup(
            pnlshowMinutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlshowMinutesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinutesShow, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlshowMinutesLayout.setVerticalGroup(
            pnlshowMinutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlshowMinutesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblMinutesShow, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lblMinutes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMinutes.setForeground(new java.awt.Color(0, 255, 255));
        lblMinutes.setText("Seconds");

        lblSeconds.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblSeconds.setForeground(new java.awt.Color(0, 255, 255));
        lblSeconds.setText("Minutes");

        lblMilliSeconds.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMilliSeconds.setForeground(new java.awt.Color(0, 255, 255));
        lblMilliSeconds.setText("MilliSeconds");

        btnStop.setBackground(new java.awt.Color(255, 0, 3));
        btnStop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStop.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnStop.setForeground(new java.awt.Color(243, 255, 0));
        btnStop.setLabel("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStopActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 0, 3));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReset.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(243, 255, 0));
        btnReset.setLabel("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnResetActionPerformed(evt);
            }
        });

        btnStart2.setBackground(new java.awt.Color(255, 0, 3));
        btnStart2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnStart2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnStart2.setForeground(new java.awt.Color(243, 255, 0));
        btnStart2.setLabel("Start");
        btnStart2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStart2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlshowSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMinutes, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlshowMinutes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(pnlShowMilliSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblMilliSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeconds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMilliSeconds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlshowSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlShowMilliSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlshowMinutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopActionPerformed
    {//GEN-HEADEREND:event_btnStopActionPerformed
        // TODO add your handling code here:
        ctx = System.currentTimeMillis();
        val = false;
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        // TODO add your handling code here:
        ct=1;
        lblMilliSecondsShow.setText("00");
        lblMinutesShow.setText("00");
        lblSecondsShow.setText("00");
        milli  = 0;
        sec   = 0;
        min   = 0;
        val = false;
        de =0;
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStart2ActionPerformed
    {//GEN-HEADEREND:event_btnStart2ActionPerformed
          if(ct==1)
          {
                    ctx   = System.currentTimeMillis();
                    ct     = System.currentTimeMillis();
          }
          else
          {
              de += System.currentTimeMillis()-ctx;
          }
          
            
             val = true;
             t1 = new Thread(f);
             t1.start();
             
    }//GEN-LAST:event_btnStart2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnReset;
    private java.awt.Button btnStart2;
    private java.awt.Button btnStop;
    private java.awt.Label label1;
    private java.awt.Label lblMilliSeconds;
    private java.awt.Label lblMilliSecondsShow;
    private java.awt.Label lblMinutes;
    private java.awt.Label lblMinutesShow;
    private java.awt.Label lblSeconds;
    private java.awt.Label lblSecondsShow;
    private java.awt.Panel pnlMain;
    private java.awt.Panel pnlShowMilliSeconds;
    private java.awt.Panel pnlTitle;
    private java.awt.Panel pnlshowMinutes;
    private java.awt.Panel pnlshowSeconds;
    // End of variables declaration//GEN-END:variables

    
   synchronized public void setTime()
    {
        
        
        
        
        while(val)
        {  ctx = System.currentTimeMillis();
             
            if(sec==60)
            {
                min += 1;
                ct = System.currentTimeMillis();
                if(min==60)min=0;
                de =0;
              
            }
            milli =  ((ctx-de)-ct)/100%10;
            lblMilliSecondsShow.setText(milli+"");
            sec =((ctx-de)-ct)/1000;
      
            lblSecondsShow.setText(sec+"");
            lblMinutesShow.setText(min+"");
          
            try
            {
                Thread.sleep(100);
            }
            catch (Exception e)
            {
                
            }
        }
    }
    
    public void run()
    {
        setTime();
    }


}


