/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design_1;

import java.awt.CheckboxGroup;

/**
 *
 * @author lenovo
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame
     */
    MainFrame f ;
    public MainFrame()
    {
        f=this;
        initComponents();
        CheckboxGroup mygrp = new CheckboxGroup();
        chkBinary.setCheckboxGroup(mygrp);
        chkHex.setCheckboxGroup(mygrp);
        chkOct.setCheckboxGroup(mygrp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlTitle = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        lblTitle = new java.awt.Label();
        pnlBody = new java.awt.Panel();
        lblDecimalnumber = new java.awt.Label();
        lblChoosenumberSystem = new java.awt.Label();
        txtDecimalNumber = new java.awt.TextField();
        pnlCheckbox = new java.awt.Panel();
        chkBinary = new java.awt.Checkbox();
        chkHex = new java.awt.Checkbox();
        chkOct = new java.awt.Checkbox();
        txtAnswer = new java.awt.TextField();
        lblAnswer = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitle.setBackground(new java.awt.Color(145, 163, 0));

        panel2.setBackground(new java.awt.Color(97, 109, 0));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(199, 255, 105));
        lblTitle.setText("Number Converter");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlBody.setBackground(new java.awt.Color(97, 109, 0));

        lblDecimalnumber.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDecimalnumber.setForeground(new java.awt.Color(199, 255, 105));
        lblDecimalnumber.setText("Enter Decimal Number");

        lblChoosenumberSystem.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblChoosenumberSystem.setForeground(new java.awt.Color(199, 255, 105));
        lblChoosenumberSystem.setText("Choose Number System");

        txtDecimalNumber.setBackground(new java.awt.Color(145, 163, 0));
        txtDecimalNumber.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtDecimalNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtDecimalNumber.setText("textField1");

        pnlCheckbox.setBackground(new java.awt.Color(140, 158, 0));

        chkBinary.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkBinary.setForeground(new java.awt.Color(107, 118, 0));
        chkBinary.setLabel("Binary");
        chkBinary.setName(""); // NOI18N
        chkBinary.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkBinaryItemStateChanged(evt);
            }
        });

        chkHex.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkHex.setForeground(new java.awt.Color(107, 118, 0));
        chkHex.setLabel("Hexadecimal");
        chkHex.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkHexItemStateChanged(evt);
            }
        });

        chkOct.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkOct.setForeground(new java.awt.Color(107, 118, 0));
        chkOct.setLabel("Octal");
        chkOct.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                chkOctItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlCheckboxLayout = new javax.swing.GroupLayout(pnlCheckbox);
        pnlCheckbox.setLayout(pnlCheckboxLayout);
        pnlCheckboxLayout.setHorizontalGroup(
            pnlCheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkOct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCheckboxLayout.setVerticalGroup(
            pnlCheckboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckboxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(chkBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHex, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkOct, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        txtAnswer.setBackground(new java.awt.Color(140, 158, 0));
        txtAnswer.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(255, 255, 255));
        txtAnswer.setText("textField1");
        txtAnswer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtAnswerActionPerformed(evt);
            }
        });

        lblAnswer.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(255, 0, 3));
        lblAnswer.setName(""); // NOI18N
        lblAnswer.setText("Answer :");

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDecimalNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDecimalnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChoosenumberSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChoosenumberSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDecimalnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txtDecimalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtAnswerActionPerformed
    {//GEN-HEADEREND:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void chkBinaryItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkBinaryItemStateChanged
    {//GEN-HEADEREND:event_chkBinaryItemStateChanged
        
        int n =0;
        try{
            n = Integer.parseInt( txtDecimalNumber.getText());
            String ans = Integer.toBinaryString(n);
            txtAnswer.setText(ans);

        }
        catch(Exception e)
        {
                txtAnswer.setText("0");
                MainDialog d = new MainDialog(f);
                Thread t = new Thread(d);
                t.start();
                
        }
      
        
        
    }//GEN-LAST:event_chkBinaryItemStateChanged

    private void chkHexItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkHexItemStateChanged
    {//GEN-HEADEREND:event_chkHexItemStateChanged
        // TODO add your handling code here:
               
      
      
          
        int n =0;
        try{
            n = Integer.parseInt( txtDecimalNumber.getText());
           String ans = Integer.toHexString(n);
            txtAnswer.setText(ans);

        }
        catch(Exception e)
        {
                txtAnswer.setText("0");
                MainDialog d = new MainDialog(f);
                Thread t = new Thread(d);
                t.start();
                
        }
    }//GEN-LAST:event_chkHexItemStateChanged

    private void chkOctItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_chkOctItemStateChanged
    {//GEN-HEADEREND:event_chkOctItemStateChanged
        // TODO add your handling code here:


        int n =0;
        try{
            n = Integer.parseInt( txtDecimalNumber.getText());
                  
       String ans = Integer.toOctalString(n);
            txtAnswer.setText(ans);

        }
        catch(Exception e)
        {
                txtAnswer.setText("0");
                MainDialog d = new MainDialog(f);
                Thread t = new Thread(d);
                t.start();
                
        }
       
    }//GEN-LAST:event_chkOctItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox chkBinary;
    private java.awt.Checkbox chkHex;
    private java.awt.Checkbox chkOct;
    private java.awt.Label lblAnswer;
    private java.awt.Label lblChoosenumberSystem;
    private java.awt.Label lblDecimalnumber;
    private java.awt.Label lblTitle;
    private java.awt.Panel panel2;
    private java.awt.Panel pnlBody;
    private java.awt.Panel pnlCheckbox;
    private java.awt.Panel pnlTitle;
    private java.awt.TextField txtAnswer;
    private java.awt.TextField txtDecimalNumber;
    // End of variables declaration//GEN-END:variables
}
